### ISSUE TITLE
About sharp

### ISSUE THREAD

**Issue by AlainGourves** [xVanTuring/cquant#7]
First of all, great work ! It is indeed super fast, even on a Raspberry Pi.

I have just a small observation : you rely on `sharp` as it is noted in the basic example, but it’s not part of the dependencies. So the example produces en error (`Error: Cannot find module ‘sharp’`).

**Comment by xVanTuring** [comment]
Well,First of all, thank you for using cquant.
I remove the sharp from the `package.json`, because some people might not want to use sharp, and they should install sharp manually(which sounds like a peerDependencies?). Anyway, I will add the step of installing sharp, thanks for your help

**Comment by xVanTuring** [comment]
Add step of install sharp: d81ec861db302d886b2783bfcf050b03b190139d. 
Closing issue, feel to reopen it if you have any troubles
